export const GET_NEXT_FIVE_POKEMONES = 'GET_NEXT_FIVE_POKEMONES';
export const POST_ITEM = 'POST_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';

//API
export const POCKEMONES_FETCHING = 'POKEMONES_FETCHING';
export const POCKEMONES_FETCHED = 'POKEMONES_FETCHED';
export const POCKEMONES_FETCH_FAILED = 'POKEMONES_FETCH_FAILED';

//Abilities
export const POKEMON_ABILITIES = 'POKEMON_ABILITIES';
